language: node_js
node_js:
  - '9.3.0'
script:
  - npm run build
after_script:
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "Update website"
  - git push 